# Generated by Django 5.0.4 on 2024-04-19 21:31

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Enter any notes about the plan', max_length=1000, null=True)),
                ('scheduled_start_date_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_date_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scheduled_start_date_time', 'description'],
            },
        ),
        migrations.CreateModel(
            name='PlanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the plan's status (e.g. Idea, Booked, Canceled, etc.)", max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a plan type (e.g. Flight, Hotel, Activity, etc.)', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Enter any notes about the todo', max_length=1000, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['due_date', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('goal_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Enter any notes about the trip', max_length=1000, null=True)),
            ],
            options={
                'ordering': ['destination'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('notes', models.TextField(help_text='Enter any notes about the budget item', max_length=1000, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('type', models.CharField(blank=True, choices=[('es', 'Estimated'), ('ac', 'Actual'), ('ex', 'Expended')], default='es', help_text='Budget Item Type', max_length=2)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Planner.plan')),
            ],
            options={
                'ordering': ['due_date', 'description'],
            },
        ),
        migrations.AddConstraint(
            model_name='planstatus',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='planstatus_name_case_insensitive_unique', violation_error_message='Plan Status already exists (case insensitive match)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Planner.planstatus'),
        ),
        migrations.AddConstraint(
            model_name='plantype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='plantype_name_case_insensitive_unique', violation_error_message='Plan Type already exists (case insensitive match)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Planner.plantype'),
        ),
        migrations.AddField(
            model_name='todo',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Planner.plan'),
        ),
        migrations.AddField(
            model_name='todo',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planner.trip'),
        ),
        migrations.AddField(
            model_name='plan',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planner.trip'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planner.trip'),
        ),
    ]
