# Generated by Django 5.0.4 on 2024-04-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', '0002_alter_budgetitem_plan_alter_todo_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter any notes about the budget item', max_length=1000, null=True),
        ),
    ]
